version: '3.1'

services:
  mssql: 
    build: 
      context: ./db
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./db/data:/var/opt/mssql/data:rw
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_TCP_PORT=$DB_PORT

  server: 
    build: 
      context: ./server
    volumes:
      - ./server/logs:/var/log/cabal
    tty : true
    depends_on:
      - mssql
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CONFIG_TYPE=${CONFIG_TYPE}
      - EXP_RATE=$EXP_RATE
      - SEXP_RATE=$SEXP_RATE
      - CEXP_RATE=$CEXP_RATE
      - DROP_RATE=$DROP_RATE
      - ALZ_RATE=$ALZ_RATE
      - BALZ_RATE=$BALZ_RATE
      - PEXP_RATE=$PEXP_RATE
      - ITEMS_PER_DROP=$ITEMS_PER_DROP
    ports:
      - 38101:38101
      - 38190:38190
      - 38170:38170
      - 38121:38121
      - 38181:38181
      - 38180:38180
      - 38111-38120:38111-38120

  site:
    build:
      context: ./site
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mssql
      - DB_CONNECTION=account
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_ACCOUNT_DATABASE=account
      - DB_GAMEDB_DATABASE=gamedb
      - DB_USERNAME=sa
      - APP_NAME="CABAL EP2 GM PANEL"
      - APP_KEY=base64:zCa+42BpJX1LCXXXN5I3dPfBEIrvrVnwL9CJwsvSO1w=
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./site:/var/www
    depends_on:
      - mssql

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./site:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - site